version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - postgresdb-data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_DB=rpctools
      - POSTGRES_USER=rpc
      - POSTGRES_PASSWORD=abcd1234
      - POSTGRES_HOST_AUTH_METHOD=trust

  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    command: sleep infinity
    volumes:
      - .:/workspace
    ports:
      - "8888:8000"
    environment:
      - POSTGRES_DB=rpctools
      - POSTGRES_USER=rpc
      - POSTGRES_PASSWORD=abcd1234
      - RPC_API_TOKEN=devtoken
      # OIDC RP client credential for dev instance of datatracker (not secret for dev, will be for production)
      - OIDC_RP_CLIENT_ID=502412
      - OIDC_RP_CLIENT_SECRET=4046925638956f0d733cd96a5a89646815f0e989c878e9e09475b2f8
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
        - PGADMIN_DEFAULT_EMAIL=dev@ietf.org
        - PGADMIN_DEFAULT_PASSWORD=dev
        - PGADMIN_CONFIG_LOGIN_BANNER="Login with dev@ietf.org / dev"
        - PGADMIN_DISABLE_POSTFIX=True
        - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
        - SCRIPT_NAME=/pgadmin
    volumes:
        - ./docker/configs/pgadmin-servers.json:/pgadmin4/servers.json

volumes:
  postgresdb-data:
