version: '3.8'

# Relies on secrets.env containing
#  - POSTGRES_PASSWORD
#  - OIDC_RP_CLIENT_ID
#  - OIDC_RP_CLIENT_SECRET
#
services:
  db:
    image: postgres:14
    volumes:
      - postgresdb-data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_DB=rpctools
      - POSTGRES_USER=rpc
      - POSTGRES_PASSWORD=abcd1234
      - POSTGRES_HOST_AUTH_METHOD=trust

  rfced:
    build:
      context: .
      dockerfile: docker/rfced.Dockerfile
    volumes:
      - rfced-data:/var/lib/mysql
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=abcd1234
      - MARIADB_DATABASE=rfced

  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    command: sleep infinity
    volumes:
      - .:/workspace
    ports:
      - "8888:8000"
    env_file:
      - secrets.env
    environment:
      - MARIADB_USER=root
      - MARIADB_PASSWORD=abcd1234
      - MARIADB_DATABASE=rfced
      - POSTGRES_DB=rpctools
      - POSTGRES_USER=rpc
      - POSTGRES_PASSWORD=abcd1234
      - RPC_API_TOKEN=devtoken
    depends_on:
      - db
      - rfced
    extra_hosts:
      - "host.docker.internal:host-gateway"

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
        - PGADMIN_DEFAULT_EMAIL=dev@ietf.org
        - PGADMIN_DEFAULT_PASSWORD=dev
        - PGADMIN_CONFIG_LOGIN_BANNER="Login with dev@ietf.org / dev"
        - PGADMIN_DISABLE_POSTFIX=True
        - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
        - SCRIPT_NAME=/pgadmin
    volumes:
        - ./docker/configs/pgadmin-servers.json:/pgadmin4/servers.json

volumes:
  postgresdb-data:
  rfced-data:
