[tool.ruff]
target-version = "py312"
line-length = 88

[tool.ruff.format]
docstring-code-line-length = 100
indent-style = "space"  # Use spaces for indentation
quote-style = "double"

[tool.ruff.lint]
extend-select = [
    "E",   # pycodestyle
    "F",   # Pyflakes
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "I",   # isort
]
extend-ignore = [
    "F405",  # variable may be undefined, or defined from star imports
    "F403",  # unable to detect undefined names
]
