namespace: rpc
configMapGenerator:
  - name: rpc-files-cfgmap
    files:
      - nginx-logging.conf
#      - nginx-datatracker.conf
      - nginx-purple.conf
#      - settings_local.py
resources:
#  - datatracker.yaml
  - purple.yaml
