# Generated by Django 5.2.1 on 2025-06-06 20:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rpc", "0008_alter_historicallabel_slug_alter_label_slug"),
    ]

    operations = [
        migrations.DeleteModel(
            name="IanaAction",
        ),
    ]
