# Generated by Django 5.2.10 on 2026-01-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpc', '0008_populate_blockingreasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrfctobe',
            name='consensus',
            field=models.BooleanField(default=False, help_text='Whether document has consensus'),
        ),
        migrations.AddField(
            model_name='rfctobe',
            name='consensus',
            field=models.BooleanField(default=False, help_text='Whether document has consensus'),
        ),
    ]
