# Generated by Django 5.2.1 on 2025-06-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatracker', '0002_initial'),
        ('rpc', '0011_delete_ianaaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalrfctobe',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical rfc to be', 'verbose_name_plural': 'historical rfc to bes'},
        ),
        migrations.AlterModelOptions(
            name='rfctobe',
            options={},
        ),
        migrations.AddConstraint(
            model_name='rfctobe',
            constraint=models.UniqueConstraint(condition=models.Q(('rfc_number__isnull', False)), fields=('rfc_number',), name='unique_non_null_rfc_number'),
        ),
    ]
