# Generated by Django 5.2.13 on 2026-04-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpc', '0020_clustermember_order_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirtyBits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('rfcindex', 'RFC Index')], max_length=40, unique=True)),
                ('dirty_time', models.DateTimeField(blank=True, null=True)),
                ('processed_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'dirty bits',
            },
        ),
    ]
