/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdditionalEmailRequest
 */
export interface AdditionalEmailRequest {
    /**
     * 
     * @type {string}
     * @memberof AdditionalEmailRequest
     */
    email: string;
}

/**
 * Check if a given object implements the AdditionalEmailRequest interface.
 */
export function instanceOfAdditionalEmailRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;

    return isInstance;
}

export function AdditionalEmailRequestFromJSON(json: any): AdditionalEmailRequest {
    return AdditionalEmailRequestFromJSONTyped(json, false);
}

export function AdditionalEmailRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdditionalEmailRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function AdditionalEmailRequestToJSON(value?: AdditionalEmailRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
    };
}

