/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdditionalEmail
 */
export interface AdditionalEmail {
    /**
     * 
     * @type {number}
     * @memberof AdditionalEmail
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof AdditionalEmail
     */
    email: string;
    /**
     * 
     * @type {number}
     * @memberof AdditionalEmail
     */
    readonly rfcToBe?: number;
}

/**
 * Check if a given object implements the AdditionalEmail interface.
 */
export function instanceOfAdditionalEmail(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;

    return isInstance;
}

export function AdditionalEmailFromJSON(json: any): AdditionalEmail {
    return AdditionalEmailFromJSONTyped(json, false);
}

export function AdditionalEmailFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdditionalEmail {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'email': json['email'],
        'rfcToBe': !exists(json, 'rfc_to_be') ? undefined : json['rfc_to_be'],
    };
}

export function AdditionalEmailToJSON(value?: AdditionalEmail | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
    };
}

