/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedAdditionalEmailRequest
 */
export interface PatchedAdditionalEmailRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedAdditionalEmailRequest
     */
    email?: string;
}

/**
 * Check if a given object implements the PatchedAdditionalEmailRequest interface.
 */
export function instanceOfPatchedAdditionalEmailRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedAdditionalEmailRequestFromJSON(json: any): PatchedAdditionalEmailRequest {
    return PatchedAdditionalEmailRequestFromJSONTyped(json, false);
}

export function PatchedAdditionalEmailRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedAdditionalEmailRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': !exists(json, 'email') ? undefined : json['email'],
    };
}

export function PatchedAdditionalEmailRequestToJSON(value?: PatchedAdditionalEmailRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
    };
}

