/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Serializer for related document for an RfcToBe
 * @export
 * @interface RpcRelatedDocument
 */
export interface RpcRelatedDocument {
    /**
     * 
     * @type {number}
     * @memberof RpcRelatedDocument
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof RpcRelatedDocument
     */
    relationship: string;
    /**
     * 
     * @type {string}
     * @memberof RpcRelatedDocument
     */
    readonly draftName?: string;
    /**
     * 
     * @type {string}
     * @memberof RpcRelatedDocument
     */
    readonly targetDraftName?: string;
}

/**
 * Check if a given object implements the RpcRelatedDocument interface.
 */
export function instanceOfRpcRelatedDocument(value: object): value is RpcRelatedDocument {
    if (!('relationship' in value) || value['relationship'] === undefined) return false;
    return true;
}

export function RpcRelatedDocumentFromJSON(json: any): RpcRelatedDocument {
    return RpcRelatedDocumentFromJSONTyped(json, false);
}

export function RpcRelatedDocumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcRelatedDocument {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'relationship': json['relationship'],
        'draftName': json['draft_name'] == null ? undefined : json['draft_name'],
        'targetDraftName': json['target_draft_name'] == null ? undefined : json['target_draft_name'],
    };
}

export function RpcRelatedDocumentToJSON(json: any): RpcRelatedDocument {
    return RpcRelatedDocumentToJSONTyped(json, false);
}

export function RpcRelatedDocumentToJSONTyped(value?: Omit<RpcRelatedDocument, 'id'|'draft_name'|'target_draft_name'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'relationship': value['relationship'],
    };
}

