name: Publish Wiki
on:
  push:
    branches: [main]
    paths:
      - client/app/components/**
      - docs/docgen.config.js
      - docs/package.json
      - docs/package-lock.json
      - .github/workflows/publish-wiki.yml
  workflow_dispatch:
concurrency:
  group: publish-wiki
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v5.0.0
        with:
          node-version: 22.x
      - name: Generate Markdown
        working-directory: docs
        run: |
          npm ci
          npm run build
      - name: Publish wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v5
        with:
          path: docs/output

