name: Purple Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Check code style black
      run: |
        pip install black
        black --check --diff .

    - name: Check code style ruff
      run: |
        pip install ruff
        ruff check .


