name: Purple Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - uses: actions/setup-python@v6
      with:
        python-version: "3.12"

    - name: Install Ruff
      run: pip install ruff

    - name: Check code format
      run: |
        ruff format --check --diff .

    - name: Check code style and linting
      run: |
        ruff check .
