name: Purple Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Check code style
      run: |
        pip install black
        black --check .

    - name: Static code analysis
      run: |
        pip install pyflakes
        pyflakes datatracker purple rpc rpcauth utils

